{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.collector.serviceAccount }}
  labels:
    {{- include "opentelemetry.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.collector.serviceAccount }}
  labels:
    {{- include "opentelemetry.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.collector.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.collector.serviceAccount }}
  labels:
    {{- include "opentelemetry.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.collector.serviceAccount }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.collector.serviceAccount }}
    namespace: {{ .Release.Namespace }}
{{- end }}
