{{- if .Values.enabled }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.global.s3.adminAuth.secretName -}}
{{- $adminAccessKeyId := "" }}
{{- $adminSecretAccessKey := "" }}
{{- if .Values.global.s3.adminAuth.accessKeyId }}
  {{- $adminAccessKeyId = .Values.global.s3.adminAuth.accessKeyId }}
{{- else if and $secret $secret.data.access_key_id }}
  {{- $adminAccessKeyId = $secret.data.access_key_id | b64dec }}
{{- else }}
  {{- $adminAccessKeyId = randAlphaNum 20 }}
{{- end }}
{{- if .Values.global.s3.adminAuth.secretAccessKey }}
  {{- $adminSecretAccessKey = .Values.global.s3.adminAuth.secretAccessKey }}
{{- else if and $secret $secret.data.secret_access_key }}
  {{- $adminSecretAccessKey = $secret.data.secret_access_key | b64dec }}
{{- else }}
  {{- $adminSecretAccessKey = randAlphaNum 40 }}
{{- end }}


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.filer.s3.configSecret.name }}
  labels:
    {{- include "seaweed.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.filer.s3.configSecret.key }}: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": "{{ $adminAccessKeyId }}",
              "secretKey": "{{ $adminSecretAccessKey }}"
            }
          ],
          "actions": ["Admin"]
        },
        {
          "name": "anonymous",
          "actions": []
        }
      ]
    }
---
# Secret for admin credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.s3.adminAuth.secretName }}
  labels:
    {{- include "seaweed.labels" $ | nindent 4 }}
type: Opaque
stringData:
  access_key_id: {{ $adminAccessKeyId | quote }}
  secret_access_key: {{ $adminSecretAccessKey | quote }}
  credentials_json: {{ dict "access_key_id" $adminAccessKeyId "secret_access_key" $adminSecretAccessKey | toJson | quote }}
{{- end }}