{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.admin.passwordSecretName }}
{{- if .Values.enabled }}
# Admin secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.admin.passwordSecretName }}
  labels:
    {{- include "cnpg-databases.labels" . | nindent 4 }}
    app: postgres
type: Opaque
stringData:
  username: {{ .Values.admin.username | quote }}
  {{- if .Values.admin.password }}
  password: {{ .Values.admin.password | quote }}
  {{- else if and $secret $secret.data.password }}
  password: {{ $secret.data.password | b64dec | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | quote }}
  {{- end }}

{{- range .Values.databases }}
---
# Secret for {{ .name }}
{{- $dbSecret := lookup "v1" "Secret" $.Release.Namespace .passwordSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .passwordSecretName }}
  labels:
    {{- include "cnpg-databases.labels" $ | nindent 4 }}
    app: postgres
    database: {{ .name }}
    cnpg.io/reload: "true"
type: Opaque
stringData:
  username: {{ .owner | quote }}
  {{- if and $dbSecret $dbSecret.data.password }}
  password: {{ $dbSecret.data.password | b64dec | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- end }}

{{- with .Values.global.spicedb.database }}
---
# Secret for {{ .name }}
{{- $dbSecret := lookup "v1" "Secret" $.Release.Namespace .passwordSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .passwordSecretName }}
  labels:
    {{- include "cnpg-databases.labels" $ | nindent 4 }}
    app: postgres
    database: {{ .name }}
    cnpg.io/reload: "true"
type: Opaque
stringData:
  username: {{ .owner | quote }}
  {{- if and $dbSecret $dbSecret.data.password }}
  password: {{ $dbSecret.data.password | b64dec | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- end }}

{{- with .Values.global.keycloak.database }}
---
# Secret for {{ .name }}
{{- $dbSecret := lookup "v1" "Secret" $.Release.Namespace .passwordSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .passwordSecretName }}
  labels:
    {{- include "cnpg-databases.labels" $ | nindent 4 }}
    app: postgres
    database: {{ .name }}
    cnpg.io/reload: "true"
type: Opaque
stringData:
  username: {{ .owner | quote }}
  {{- if and $dbSecret $dbSecret.data.password }}
  password: {{ $dbSecret.data.password | b64dec | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- end }}
{{- end }}
