{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" (include "platform-orchestrator.fullname" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-orchestrator.fullname" . }}-secrets
  labels:
    {{- include "platform-orchestrator.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- if and $secret $secret.data.runnerTokenSalt }}
  runnerTokenSalt: {{ $secret.data.runnerTokenSalt | b64dec | quote }}
  {{- else }}
  runnerTokenSalt: {{ randAlphaNum 32 | quote }}
  {{- end }}
  {{- if and $secret $secret.data.ssoStateSecret }}
  ssoStateSecret: {{ $secret.data.ssoStateSecret | b64dec | quote }}
  {{- else }}
  ssoStateSecret: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- if .Values.global.enableAdminApi }}
  {{- if and $secret $secret.data.superUserToken }}
  superUserToken: {{ $secret.data.superUserToken | b64dec | quote }}
  {{- else }}
  superUserToken: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- else }}
  superUserToken: ""
{{- end }}
