apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{ include "rabbitmq.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
