apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: {{ include "rabbitmq.fullname" . }}-platform-vhost
  labels:
    {{ include "rabbitmq.labels" . | nindent 4 }}
spec:
  vhost: {{ .Values.vhost.name }}
  userReference:
    name: {{ include "rabbitmq.fullname" . }}-platform
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: {{ include "rabbitmq.fullname" . }}
