apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{ include "rabbitmq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
  resources:
    {{ toYaml .Values.resources | nindent 4 }}
  rabbitmq:
    additionalConfig: |
      {{- .Values.additionalConfig | nindent 6 }}
  persistence:
    storageClassName: {{ .Values.persistence.storageClassName }}
    storage: {{ .Values.persistence.storage }}
  {{- with .Values.affinity }}
  affinity:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  override:
    statefulSet:
      spec:
        template:
          metadata:
            annotations:
              {{ toYaml .Values.override.annotations | nindent 14 }}
          spec:
            containers: []
            {{- if .Values.override.topologySpreadConstraints }}
            topologySpreadConstraints:
              {{- range .Values.override.topologySpreadConstraints }}
              - maxSkew: {{ .maxSkew | default 1 }}
                topologyKey: {{ .topologyKey }}
                whenUnsatisfiable: {{ .whenUnsatisfiable | default "DoNotSchedule" }}
                labelSelector:
                  matchLabels:
                    {{ include "rabbitmq.selectorLabels" $ | nindent 20 }}
              {{- end }}
            {{- end }}
