apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: {{ .Values.vhost.name }}
  labels:
    {{ include "rabbitmq.labels" . | nindent 4 }}
spec:
  name: {{ .Values.vhost.name }}
  rabbitmqClusterReference:
    name: {{ include "rabbitmq.fullname" . }}
