apiVersion: v2
name: platform-orchestrator
description: Platform Orchestrator
type: application
version: 0.6.0
appVersion: "3.3.0"

annotations:
  org.opencontainers.image.source: https://github.com/stellwerk-labs/platform-orchestrator-helm-chart

dependencies:
  - name: backend-module
    alias: control-plane
    version: "0.1.0"
  - name: backend-module
    alias: data-plane
    version: "0.1.0"
  - name: backend-module
    alias: iam
    version: "0.1.0"
  - name: console
    version: "0.1.0"
  - name: cnpg-databases
    version: "0.1.0"
    condition: cnpg-databases.enabled
  - name: nats
    version: "2.14.0"
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled
  - name: keycloak
    version: "0.1.0"
    condition: keycloak.enabled
