{{- $thisSecret := lookup "v1" "Secret" .Release.Namespace .Values.bootstrapAdmin.secretName }}
{{- $username := "admin" }}
{{- $password := randAlphaNum 32 }}
{{- if and $thisSecret $thisSecret.data.username }}
{{- $username = $thisSecret.data.username | b64dec }}
{{- end }}
{{- if and $thisSecret $thisSecret.data.password }}
{{- $password = $thisSecret.data.password | b64dec }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bootstrapAdmin.secretName }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
---
{{- $clientSecret := lookup "v1" "Secret" .Release.Namespace .Values.global.keycloak.realm.clientSecretName }}
{{- $clientSecretValue := randAlphaNum 32 }}
{{- if and $clientSecret $clientSecret.data.clientSecret }}
{{- $clientSecretValue = $clientSecret.data.clientSecret | b64dec }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.keycloak.realm.clientSecretName }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ $clientSecretValue | quote }}
